version: '3.7'

services:
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - prometheus
    volumes:
      - ./data/:/var/lib/grafana
    user: "0"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    ports:
      - 9100:9100
    networks:
      - prometheus

networks:
  prometheus:

volumes:
  prometheus_data: